name: Update Site
on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:     # Adds manual trigger
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Run script
        run: node fetch-articles.js
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull origin main --rebase  # Fetch and rebase local changes on top of remote
          git add public/
          git commit -m "Update site" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
